name: birdart_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog:
    git:
      url: https://github.com/sun-jiao/dart_frog.git
      ref: fix773
      path: packages/dart_frog

  session_shelf:
    path: ../../session_shelf/

  shared:
    path: ../shared

  floor: ^1.4.2
  postgresql2: ^1.5.1

dev_dependencies:
  build_runner: ^2.4.5
  floor_generator: ^1.4.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
