name: birdart_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog:
    git:
      url: https://github.com/sun-jiao/dart_frog.git
      ref: fix773
      path: packages/dart_frog

  drift_postgres: ^1.2.0
  image: ^4.1.7
  session_shelf:
    path: ../../session_shelf/

  shared:
    path: ../shared


dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.3
  very_good_analysis: ^5.1.0
