name: birdart_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/birdarts/birdart

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  package:
    path: ../package

  args: ^2.3.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2

dev_dependencies:
  http: ^1.0.0
  lints: ^2.0.1
  test: ^1.24.3
