name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  floor_annotation: ^1.4.2
  uuid: ^4.3.3
  latlong2: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
