name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  cryptography: ^2.7.0
  drift: ^2.16.0
  json_annotation: ^4.8.1
  uuid: ^4.4.0
  latlong2: any

dev_dependencies:
  build_runner: ^2.4.9
  drift_dev: ^2.16.0
  lints: ^3.0.0
  test: ^1.25.3
